const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function nav(view){$$('.view').forEach(x=>x.classList.remove('active'));const v=$('#'+view);if(v)v.classList.add('active');$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));window.scrollTo(0,0)}
$$('[data-view]').forEach(x=>x.addEventListener('click',e=>{const v=e.currentTarget.dataset.view;if(v)nav(v)}));
$('#profileToggle').onclick=()=>$('#profileMenu').classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('#profileToggle')&&!e.target.closest('#profileMenu'))$('#profileMenu').classList.remove('open')});$('#logout').onclick=()=>{alert('Anda telah keluar.');$('#profileMenu').classList.remove('open')};
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('buy'));b.classList.add('buy');});$('#deposit')?.addEventListener('click',()=>alert('Deposit siap diproses pada versi server.'));$('#withdraw')?.addEventListener('click',()=>alert('Withdrawal siap diproses pada versi server.'));
function Ticker(){return null}
const tickers=[['₿','BTC/IDR','Rp 1.850.000.000','+1,23%'],['◆','ETH/IDR','Rp 65.000.000','+2,45%'],['₮','USDT/IDR','Rp 16.250','+0,12%'],['S','SOL/IDR','Rp 2.450.000','+3,18%'],['B','BNB/IDR','Rp 8.250.000','+0,95%']];
const t=document.createElement('div');t.className='ticker';t.innerHTML=tickers.map(x=>`<div class="tick"><b>${x[0]} ${x[1]}</b><span>${x[2]} &nbsp; <i class="gain">${x[3]}</i></span></div>`).join('');$('.hero').after(t);
function Balance(p){return null}
const balHtml=(s,n,c,v,sub='')=>`<div class="balance"><span class="symbol">${s}</span><div class="name"><b>${n}</b> <small>${c}</small></div><div><strong>${v}</strong>${sub?`<small>${sub}</small>`:''}</div></div>`;
$$('.balances').forEach(el=>{if(!el.querySelector('.balance'))el.innerHTML+=balHtml('Rp','Rupiah','IDR','Rp 10.000.000')+balHtml('₿','Bitcoin','BTC','0,00250000','Rp 4.625.000')+balHtml('◆','Ethereum','ETH','0,01500000','Rp 975.000')+balHtml('₮','Tether','USDT','50,000000','Rp 812.500')});
function TradeBox(){return null}
const boxes=$$('.tradebox');boxes.forEach(b=>{b.innerHTML=`<div class="tabs"><button class="buy">Beli</button><button>Jual</button></div><select><option>₿ BTC &nbsp; Bitcoin</option><option>◆ ETH &nbsp; Ethereum</option><option>₮ USDT &nbsp; Tether</option></select><small>Harga Terakhir</small><h3>Rp 1.850.000.000 <span class="gain">+1,23%</span></h3><small>Jumlah Pembelian (IDR)</small><input value="100000"><button class="buybtn">Beli BTC</button>`});
function MarketTable(){return null}
const rows=[['₿','Bitcoin','BTC','Rp 1.850.000.000','+1,23%'],['◆','Ethereum','ETH','Rp 65.000.000','+2,45%'],['₮','Tether','USDT','Rp 16.250','+0,12%'],['S','Solana','SOL','Rp 2.450.000','+3,18%'],['B','BNB','BNB','Rp 8.250.000','+0,95%'],['X','XRP','XRP','Rp 12.500','+1,12%']];
const table=`<table class="market-table"><thead><tr><th>#</th><th>Nama</th><th>Harga</th><th>Perubahan 24 Jam</th><th>Grafik</th><th>Aksi</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td><b>${r[0]} &nbsp;${r[1]}</b> <small>${r[2]}</small></td><td>${r[3]}</td><td class="gain">${r[4]}</td><td class="spark">⌁⌁⌁⌁</td><td class="action"><button class="buy">Beli</button><button class="sell">Jual</button></td></tr>`).join('')}</tbody></table>`;
$$('.market').forEach(el=>{if(!el.querySelector('.market-table'))el.innerHTML+=table});$('#search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('.market-table tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')});
