const ADMIN_EMAIL="admin@triv.web.id",ADMIN_PASSWORD="TrivAdmin@2026!",SESSION_HOURS=12;
const BANKS=["Bank Mandiri", "Bank Rakyat Indonesia (BRI)", "Bank Negara Indonesia (BNI)", "Bank Tabungan Negara (BTN)", "Bank Central Asia (BCA)", "Bank CIMB Niaga", "Bank Danamon", "Bank Permata", "Bank Panin", "Bank Maybank Indonesia", "Bank OCBC NISP", "Bank UOB Indonesia", "Bank Mega", "Bank Sinarmas", "Bank SMBC Indonesia", "Bank Jago", "Bank Neo Commerce", "Bank Seabank Indonesia", "Bank Amar Indonesia", "Bank Aladin Syariah", "Bank Syariah Indonesia (BSI)", "Bank Muamalat Indonesia", "Bank Mega Syariah", "Bank BCA Syariah", "Bank Panin Dubai Syariah", "Bank BJB", "Bank Jateng", "Bank Jatim", "Bank DIY", "Bank BPD Bali", "Bank Sumut", "Bank Sumsel Babel", "Bank Nagari", "Bank Riau Kepri", "Bank Lampung", "Bank Jambi", "Bank Bengkulu", "Bank Kalbar", "Bank Kalsel", "Bank Kalteng", "Bank Kaltimtara", "Bank Kaltara", "Bank Sulselbar", "Bank Sultra", "Bank Sulteng", "Bank SulutGo", "Bank Maluku Malut", "Bank Papua", "Bank Aceh Syariah", "Bank NTB Syariah", "Bank NTT", "Bank Woori Saudara", "Bank ICBC Indonesia", "Bank Shinhan Indonesia", "Bank DBS Indonesia", "Bank Citibank Indonesia", "Bank HSBC Indonesia", "Bank Standard Chartered Indonesia"];
function doGet(e){setup();const p=e.parameter||{},a=p.action||"";try{if(a=="banks")return J({ok:true,banks:BANKS,destinations:rows("dest").filter(active_)});if(a=="register")return register_(p);if(a=="login")return login_(p);if(a=="member")return member_(p);if(a=="account")return account_(p);if(a=="deposit")return deposit_(p);if(a=="withdraw")return withdraw_(p);if(a=="admin_login")return adminLogin_(p);if(a=="admin_data")return adminData_(p);if(a=="review")return review_(p);if(a=="add_dest")return addDest_(p);if(a=="disable_dest")return disableDest_(p);return J({ok:true,service:"Triv API"});}catch(x){return J({ok:false,error:String(x)});}}
function setup(){const ss=SpreadsheetApp.getActive(),d={admins:["email","passwordHash","active","createdAt"],users:["id","name","email","passwordHash","balance","bank","accountNumber","accountHolder","createdAt"],dest:["id","bank","accountNumber","accountHolder","label","active","createdAt"],deposits:["id","email","destinationId","bank","amount","reference","status","createdAt","reviewedAt","reviewedBy"],withdrawals:["id","email","bank","accountNumber","accountHolder","amount","note","status","createdAt","reviewedAt","reviewedBy"],notifications:["email","title","message","createdAt"]};Object.keys(d).forEach(n=>{let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()==0)s.appendRow(d[n]);});let a=ss.getSheetByName("admins");if(a.getLastRow()==1)a.appendRow([ADMIN_EMAIL,sha_(ADMIN_PASSWORD),true,new Date()]);}
function register_(p){const e=String(p.email||"").trim().toLowerCase(),pw=String(p.password||"");if(!e||pw.length<6)return J({ok:false,error:"Email dan password minimal 6 karakter."});if(rows("users").some(x=>String(x.email).toLowerCase()==e))return J({ok:false,error:"Email sudah terdaftar."});SpreadsheetApp.getActive().getSheetByName("users").appendRow([Utilities.getUuid(),p.name||"",e,sha_(pw),0,"","","",new Date()]);return login_({email:e,password:pw});}
function login_(p){const e=String(p.email||"").trim().toLowerCase(),u=rows("users").find(x=>String(x.email).toLowerCase()==e&&String(x.passwordHash)==sha_(String(p.password||"")));if(!u)return J({ok:false,error:"Email atau password salah."});return J({ok:true,token:sess_("m",e),user:pub_(u)});}
function member_(p){const s=auth_(p.token,"m");if(!s)return J({ok:false,error:"Sesi tidak valid."});const u=rows("users").find(x=>String(x.email).toLowerCase()==s.email);if(!u)return J({ok:false,error:"Akun tidak ditemukan."});return J({ok:true,user:pub_(u),destinations:rows("dest").filter(active_),deposits:rows("deposits").filter(x=>String(x.email).toLowerCase()==s.email).reverse(),withdrawals:rows("withdrawals").filter(x=>String(x.email).toLowerCase()==s.email).reverse()});}
function account_(p){const s=auth_(p.token,"m");if(!s)return J({ok:false,error:"Sesi tidak valid."});if(!p.bank||!p.accountNumber||!p.accountHolder)return J({ok:false,error:"Data rekening belum lengkap."});const sh=SpreadsheetApp.getActive().getSheetByName("users"),v=sh.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf("email")]).toLowerCase()==s.email){sh.getRange(i+1,h.indexOf("bank")+1).setValue(p.bank);sh.getRange(i+1,h.indexOf("accountNumber")+1).setValue(p.accountNumber);sh.getRange(i+1,h.indexOf("accountHolder")+1).setValue(p.accountHolder);return J({ok:true});}return J({ok:false,error:"Akun tidak ditemukan."});}
function deposit_(p){const s=auth_(p.token,"m");if(!s)return J({ok:false,error:"Sesi tidak valid."});const d=rows("dest").find(x=>String(x.id)==String(p.destinationId)&&active_(x)),a=Number(p.amount)||0;if(!d||a<=0)return J({ok:false,error:"Rekening tujuan atau nominal tidak valid."});SpreadsheetApp.getActive().getSheetByName("deposits").appendRow([Utilities.getUuid(),s.email,d.id,d.bank,a,p.reference||"","pending",new Date(),"",""]);notify_(s.email,"Deposit pending","Deposit menunggu persetujuan admin.");return J({ok:true,message:"Deposit PENDING. Saldo belum bertambah."});}
function withdraw_(p){const s=auth_(p.token,"m"),u=rows("users").find(x=>String(x.email).toLowerCase()==s.email),a=Number(p.amount)||0;if(!u||a<=0||a>Number(u.balance||0))return J({ok:false,error:"Saldo tidak mencukupi."});if(!p.bank||!p.accountNumber||!p.accountHolder)return J({ok:false,error:"Rekening withdrawal belum lengkap."});balance_(s.email,-a);SpreadsheetApp.getActive().getSheetByName("withdrawals").appendRow([Utilities.getUuid(),s.email,p.bank,p.accountNumber,p.accountHolder,a,p.note||"","pending",new Date(),"",""]);return J({ok:true,message:"Withdrawal PENDING. Saldo ditahan sampai admin memproses."});}
function adminLogin_(p){const e=String(p.email||"").trim().toLowerCase(),a=rows("admins").find(x=>String(x.email).toLowerCase()==e&&String(x.passwordHash)==sha_(String(p.password||""))&&active_(x));if(!a)return J({ok:false,error:"Email atau password admin salah."});return J({ok:true,token:sess_("a",e)});}
function adminData_(p){if(!auth_(p.token,"a"))return J({ok:false,error:"Sesi admin tidak valid."});return J({ok:true,banks:BANKS,destinations:rows("dest"),deposits:rows("deposits").filter(x=>x.status=="pending"),withdrawals:rows("withdrawals").filter(x=>x.status=="pending")});}
function review_(p){const s=auth_(p.token,"a");if(!s)return J({ok:false,error:"Sesi admin tidak valid."});const n=p.type=="deposit"?"deposits":"withdrawals",sh=SpreadsheetApp.getActive().getSheetByName(n),v=sh.getDataRange().getValues(),h=v[0];let row=-1;for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf("id")])==String(p.id))row=i+1;if(row<0||String(sh.getRange(row,h.indexOf("status")+1).getValue())!="pending")return J({ok:false,error:"Transaksi tidak ditemukan atau sudah diproses."});const e=String(sh.getRange(row,h.indexOf("email")+1).getValue()),a=Number(sh.getRange(row,h.indexOf("amount")+1).getValue())||0,st=p.decision=="approve"?"approved":"rejected";sh.getRange(row,h.indexOf("status")+1).setValue(st);sh.getRange(row,h.indexOf("reviewedAt")+1).setValue(new Date());sh.getRange(row,h.indexOf("reviewedBy")+1).setValue(s.email);if(n=="deposits"&&p.decision=="approve")balance_(e,a);if(n=="withdrawals"&&p.decision=="reject")balance_(e,a);notify_(e,"Status transaksi","Transaksi telah "+st+" oleh admin.");return J({ok:true,status:st});}
function addDest_(p){if(!auth_(p.token,"a"))return J({ok:false,error:"Sesi admin tidak valid."});if(!p.bank||!p.accountNumber||!p.accountHolder)return J({ok:false,error:"Data rekening tujuan belum lengkap."});SpreadsheetApp.getActive().getSheetByName("dest").appendRow([Utilities.getUuid(),p.bank,p.accountNumber,p.accountHolder,p.label||"",true,new Date()]);return J({ok:true});}
function disableDest_(p){if(!auth_(p.token,"a"))return J({ok:false,error:"Sesi admin tidak valid."});const sh=SpreadsheetApp.getActive().getSheetByName("dest"),v=sh.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf("id")])==String(p.id))sh.getRange(i+1,h.indexOf("active")+1).setValue(false);return J({ok:true});}
function active_(x){return String(x.active).toLowerCase()!="false"&&String(x.active)!="0";}
function rows(n){const sh=SpreadsheetApp.getActive().getSheetByName(n);if(!sh)return[];const v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0];return v.slice(1).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o;});}
function pub_(u){return{name:u.name,email:u.email,balance:Number(u.balance||0),bank:u.bank,accountNumber:u.accountNumber,accountHolder:u.accountHolder};}
function balance_(e,d){const sh=SpreadsheetApp.getActive().getSheetByName("users"),v=sh.getDataRange().getValues(),h=v[0];for(let i=1;i<v.length;i++)if(String(v[i][h.indexOf("email")]).toLowerCase()==e.toLowerCase()){let c=Number(v[i][h.indexOf("balance")])||0;sh.getRange(i+1,h.indexOf("balance")+1).setValue(c+d);return true;}return false;}
function notify_(e,t,m){SpreadsheetApp.getActive().getSheetByName("notifications").appendRow([e,t,m,new Date()]);}
function sha_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s).map(b=>("0"+(b&255).toString(16)).slice(-2)).join("");}
function sess_(t,e){const x=Utilities.getUuid();PropertiesService.getScriptProperties().setProperty("S_"+t+"_"+x,JSON.stringify({email:e,expires:Date.now()+SESSION_HOURS*3600000}));return x;}
function auth_(x,t){const r=PropertiesService.getScriptProperties().getProperty("S_"+t+"_"+x);if(!r)return null;const s=JSON.parse(r);if(Date.now()>s.expires)return null;return s;}
function J(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
